### ISSUE TITLE
[ER] Implement Webhook

### ISSUE THREAD

**Issue by jheiselman** [mrd0ll4r/tbotapi#2]
It would be nice to have the [webhook API](https://core.telegram.org/bots/api#setwebhook) as an option for the Telegram Bot API so there isn't the polling delay (especially during a shutdown).

**Comment by mrd0ll4r** [comment]
PR #3  implements the webhook. You can now create a bot like this:

``` go
u := url.URL{
    Host:   webhookHost + ":" + fmt.Sprint(webhookPort),
    Scheme: "https",
    Path:   apiKey,
}

api, handler, err := tbotapi.NewWithWebhook(apiKey, u.String(), pubkey)
if err != nil {
    log.Fatal(err)
}

http.HandleFunc("/"+apiKey, handler)

go func() {
    log.Fatal(http.ListenAndServeTLS("0.0.0.0:"+fmt.Sprint(webhookPort), pubkey, privkey, nil))
}()
```

(or use other addresses)
