### ISSUE TITLE
Setting a webhook without a self signed certificate

### ISSUE THREAD

**Issue by ankitbansal82** [mrd0ll4r/tbotapi#9]
I have used this api to successfully integrate with Telegram using a webhook. Thanks for coding this, Much appreciated. [My project](https://github.com/ankitbansal82/plugin_telegram)

The `tbotapi.NewWithWebhook(apiKey, webhookURL, certificate string)` method expects a non empty public certificate file. Which enforces user to pass in a self signed certificate. If I don't want to use a self signed certificate then I should be able to pass in nil for the certificate and still be able to setup a webhook?

> **Scenario where I don't need a self signed cert.**
> 
> Instead of go code handling the TLS/SSL, one of the preferred approach could be Apache or Nginx to handle the SSL and all "application go code" sitting behind it could then be working on http (instead of https). And in this case NGINX would be using a CA signed certificate which doesn't require me to pass a self signed certificate while setting up a webhook.

**Comment by mrd0ll4r** [comment]
Good to hear it was useful to you!

About your scenario: You'd still have to upload (the public part of) your certificate to the Telegram servers, that's basically what `NewWithWebhook` does. It doesn't actually start an HTTP(S) server and listens on the URL you specified, it instead returns an `http.HandlerFunc` that you can use however you want.
So in your case you'd specify the path to the certificate, `NewHandlerWithWebhook` uploads it and returns an `http.HandlerFunc`, you then start an HTTP server on whatever address/port you want and use it for that :)

For reference, this is what the [API spec](https://core.telegram.org/bots/api#setwebhook) has about webhooks. Note that providing a certificate is actually optional but we enforce it to get people to use cryptography.

EDIT: Just for clarification: The certificate does not need to be self-signed, it can be issued by any CA.
